---
title: Learning jq
author: Knut Behrends
date: '2017-12-16'
slug: Learning jq
categories: []
tags: []
---

### A grabbag of `jq` commands 


> Some notes about learning jq, the  lightweight and flexible command-line JSON processor. Maybe I'll extend and improve this blog post in the next months.

I need to be fluent with the JSON parsing tool [jq](https://stedolan.github.io/jq/).
Very often I have to interact with JSON data: When I interact with APIs,
when parsing scraped Twitter data, when doing SPARQL queries... 

Here I've saved some of my own mini-scripts and shortcuts that I have developed for my own needs. Most of it is already available in similar form, on the internet, but it is not available in a form that I found useful.



The following text snippets emerged by entering commands on the Unix command line.
This was a trial and error process.

#### Example 1 - extract tweet text

This snippet extracts the text from a file that I created by saving data from the Twitter streaming API:

```
< raw_tweets/stream__AGU17.json jq -s '[.[] | {text: .text}] ' \
   | jq  -f -r to_csv.jq  | grep -i "rstats" | sort -u
```


#### Example 2 - extract more than 1 field from tweets 

This is a variant of Example 1.

```
<raw_tweets/stream_rstats.json jq  -s  -S  '[.[] | \
   {name:  .user.name, sn: .user.screen_name, loc: .user.location, \
   url:.user.url, desc:.user.description, _fol: .user.followers_count }]'   | \
   jq  -f -r to_csv.jq

```

#### Helper function `to_csv()`

This is from a [Stackoverflow Answer](https://stackoverflow.com/a/44012345/202553) on the question *How to convert arbirtrary simple JSON to CSV using jq?*  

```

def tocsv($x):
    $x
    |(map(keys)
        |add
        |unique
        |sort
    ) as $cols
    |map(. as $row
        |$cols
        |map($row[.]|tostring)
    ) as $rows
    |$cols,$rows[]
    | @csv;

tocsv(.)


```

