---
title: Blood Pressure in the US population
author: Knut Behrends
date: '2018-02-08'
slug: bloodpressure-nhanes
categories: [health, rstats]
tags: [rstats]
draft: no
output:
  html_document:
    toc: no
    css: styles.css
    fig_caption: yes
    keep_md: no
image: /static/img/football.png
banner: img/post/thumb/football.png
summary: 'Blood Pressure in Americans, two different datasets.'
keywords:
  - Personal-Blog
  - Fun
  - rstats
  - blood-pressure
  - Health
  - Open-data
---



<div id="blood-pressure-as-a-function-of-age-and-body-weight" class="section level4">
<h4>Blood Pressure as a function of age and body weight</h4>
<div class="alert alert-info"><b>Very basic analysis of two health datasets from ~ 2010, about the  general US Population.</b>
                The data were gathered independently. One of them is a tiny teaching dataset, the other is a large study. Both datasets show that systolic blood pressure rises about 5-10 mm Hg per decade of a person &apos;s life. </div>
<p>Recently, conversations with friends and colleagues kept me thinking about blood pressure. Then I’ve remembered that weekend project from late 2017. Back then I had analysed two datasets: one available on the internet, the other available as R package NHANES on CRAN.</p>
<p>My motivation in writing this up was (1) learning more <em>ggplot</em> tricks, and more imortantly (2) gaining insights from a real data that interests me. It was also helpful to start with a small teaching dataset, then switch to a messy, much larger dataset; a real medical study.</p>
<p>Load the necessary packages. Nothing fancy here.</p>
<pre class="r"><code>library(readxl)
library(tidyverse)
library(ggthemes)
theme_set(theme_economist_white())
scale_colour_discrete &lt;- function(...) scale_color_brewer(palette=&quot;Set1&quot;)</code></pre>
<p>Download <strong>dataset 1</strong>: A tiny 11*4 table called <code>Systolic Blood Pressure</code>. It comes from <a href="http://college.cengage.com/mathematics/brase/understandable_statistics/7e/students/datasets/mlr/frames/frame.html">a book publisher’s website</a>. Maybe it is a teaching dataset; perhaps is is supplementary material for a college textbook.</p>
<p>The <a href="https://github.com/knbknb/kbehrends.netlify.com/tree/master/content">markdown version of this blog post</a> contains the necessary instructions on how to download and import the data.</p>
<p>The dataset is tiny:</p>
<pre><code>## Observations: 11
## Variables: 4
## $ blood_pressure &lt;int&gt; 132, 143, 153, 162, 154, 168, 137, 149, 159, 12...
## $ age            &lt;int&gt; 52, 59, 67, 73, 64, 74, 54, 61, 65, 46, 72
## $ weight_pounds  &lt;int&gt; 173, 184, 194, 211, 196, 220, 188, 188, 207, 16...
## $ weight         &lt;dbl&gt; 78.5, 83.5, 88.0, 95.7, 88.9, 99.8, 85.3, 85.3,...</code></pre>
<p>We can plot it in its entirety. I also fit a simple linear regression model to the data: Blood Pressure as a function of a person’s age and body weight.</p>
<p>Adding the predictions from the model to the plot:</p>
<div class="figure"><span id="fig:tiny2"></span>
<img src="/post/2018-02-08-blood-pressure_files/figure-html/tiny2-1.png" alt=" Predicted values are shown in red, observed values in black." width="864" />
<p class="caption">
Figure 1:  Predicted values are shown in red, observed values in black.
</p>
</div>
<p>The linear regression model shows a moderately strong correlation with age and weight. For a single-parameter model, (age as sole predictive variable), the predicted values would fall on the blue line. Inclusion of body weight as a second predicitve variable seems to improve the fitted values slightly, as the red dots show.</p>
<p>For the R specialists, this is the summary of the regression model:</p>
<pre><code>## 
## Call:
## lm(formula = blood_pressure ~ age + weight, data = bloodpressure)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.464 -1.195 -0.408  1.851  2.698 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)   30.994     11.944    2.59   0.0319 * 
## age            0.861      0.248    3.47   0.0084 **
## weight         0.738      0.288    2.56   0.0335 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.32 on 8 degrees of freedom
## Multiple R-squared:  0.977,  Adjusted R-squared:  0.971 
## F-statistic:  169 on 2 and 8 DF,  p-value: 2.87e-07</code></pre>
<div class="alert alert-warning">The model predicts that for every year of in a middle-aged person&apos;s life, the systolic blood pressure increases  <b>0.861 mm Hg/year</b>. That&apos;s almost 9 mm Hg per life decade! Quite a lot. </div>
<p>Is this realistic? Or is this a fictitious, simplified, toy-dataset, after all? Is the trend correct, but the value is not? In other words, is the sample nonrepresentative of the population? What is the real importance of the confounding factor, body weight?</p>
<p>Let’s try a larger dataset!</p>
</div>
<div id="nhanes-dataset" class="section level4">
<h4>NHANES dataset</h4>
<p>The <em>NHANES</em> dataset is available as an R package on <a href="https://cran.r-project.org/package=NHANES">CRAN</a>. It contains data from the US National Health and Nutrition Examination Study. I have used package version 2.1.0, specifically “NHANES 2009-2012 with adjusted weighting”. This dataset contains some corrections for undersampling racial minorities. Uncorrected data is also available, in the <em>NHANESraw</em> package.</p>
<p>See <a href="http://www.cdc.gov/nchs/nhanes.htm" class="uri">http://www.cdc.gov/nchs/nhanes.htm</a> for details.</p>
<pre class="r"><code>library(NHANES) # Body Shape + related measurements from 10000 US citizens
data(NHANES)</code></pre>
<p>The dataset is big, very big. It contains 10000 rows and 76 columns. Listing all column definitions here would waste too much screen space. I’ll concentrate on the relevant columns here.</p>
<p>Column names containing “Age”:</p>
<pre><code>## [1] &quot;Age&quot;           &quot;AgeDecade&quot;     &quot;AgeMonths&quot;     &quot;DiabetesAge&quot;  
## [5] &quot;Age1stBaby&quot;    &quot;SmokeAge&quot;      &quot;AgeFirstMarij&quot; &quot;AgeRegMarij&quot;  
## [9] &quot;SexAge&quot;</code></pre>
<p>Column names containing “Weight”:</p>
<pre><code>## [1] &quot;Weight&quot;</code></pre>
<p>Column names containing the prefix “BP” (Blood Pressure):</p>
<pre><code>## [1] &quot;BPSysAve&quot; &quot;BPDiaAve&quot; &quot;BPSys1&quot;   &quot;BPDia1&quot;   &quot;BPSys2&quot;   &quot;BPDia2&quot;  
## [7] &quot;BPSys3&quot;   &quot;BPDia3&quot;</code></pre>
<p>The participants had their Blood Pressure measured up to 3 times. These values were summarized in the <em>BPSysAve</em> column.</p>
<p>There are relatively few NA or NULL values in the dataset:</p>
<pre><code>##      Age   Weight BPSysAve BPDiaAve   BPSys1   BPDia1   BPSys2   BPDia2 
##        0       78     1449     1449     1763     1763     1647     1647 
##   BPSys3   BPDia3 
##     1635     1635</code></pre>
<p>Create a smaller NHANES dataset, <code>bloodpressure2</code>, containing relevant columns only:</p>
<pre class="r"><code>bloodpressure2 &lt;- NHANES %&gt;%
    select(BPSysAve, Age, Weight, Gender, BMI) %&gt;%
    filter(!is.na(BPSysAve), !is.na(Weight), !is.na(BMI))</code></pre>
<p>We include <em>Gender</em> and <em>BMI</em> (Body Mass Index) for later.</p>
<p>The dataset contains 8487 rows (People) and 5 columns.</p>
<p>Summary of Blood Pressure Data:</p>
<pre><code>##     BPSysAve        Age           Weight         Gender          BMI      
##  Min.   : 76   Min.   : 8.0   Min.   : 17.1   female:4270   Min.   :12.9  
##  1st Qu.:106   1st Qu.:24.0   1st Qu.: 62.2   male  :4217   1st Qu.:22.8  
##  Median :116   Median :40.0   Median : 76.1                 Median :26.6  
##  Mean   :118   Mean   :40.9   Mean   : 77.9                 Mean   :27.6  
##  3rd Qu.:127   3rd Qu.:56.0   3rd Qu.: 91.1                 3rd Qu.:31.4  
##  Max.   :226   Max.   :80.0   Max.   :230.7                 Max.   :81.2</code></pre>
<p>The maximum value of 80 for Age actually represents “Adults of age 80 and older”. See plots below.</p>
</div>
<div id="blood-pressure-by-gender" class="section level4">
<h4>Blood Pressure by Gender:</h4>
<div class="figure"><span id="fig:unnamed-chunk-8"></span>
<img src="/post/2018-02-08-blood-pressure_files/figure-html/unnamed-chunk-8-1.png" alt="Blood Pressure by Gender, NHANES Dataset." width="864" />
<p class="caption">
Figure 2: Blood Pressure by Gender, NHANES Dataset.
</p>
</div>
<p>Apparently, there is not much difference between the genders, the median BP for women is 113mmHg and for men it is 118 mmHg. Splitting by <em>age group</em> reveals a different picture.</p>
</div>
<div id="blood-pressure-by-age-group" class="section level4">
<h4>Blood Pressure by Age Group</h4>
<p>After splitting the dataset by life decade, we get this:</p>
<div class="figure"><span id="fig:plot4"></span>
<img src="/post/2018-02-08-blood-pressure_files/figure-html/plot4-1.png" alt="Blood Pressure by Age Group." width="864" />
<p class="caption">
Figure 3: Blood Pressure by Age Group.
</p>
</div>
<p>For kids below 10 years of age, Blood Pressures (BP) of Boys and Girls are equal. BP values are about 100 mm HG for most both genders. Blood Pressures of teenage boys and 20-30 year-old men are already higher their female “counterparts”. <div class="alert alert-warning"><b></b>Middle-Aged men generally have higher blood pressures than women of the same age. This remains so until late middle age, when blood pressures of women seem to catch up. The 60-70 year old women have blood pressures just as high as the men; maybe because men with cardiovalscular problems have already died away?</div></p>
<p>Blood Pressures generally increase, but is this rate really 9 mm/year, as indicated above?</p>
</div>
<div id="linear-modeling" class="section level4">
<h4>Linear modeling</h4>
<p>Fit a linear regression model (Blood Pressure as a function of Age and Body Weight) to the entire <code>bloodpressure2</code> subset, just as above for the tiny dataset :</p>
<p>For the R experts:</p>
<pre><code>## 
## Call:
## lm(formula = BPSysAve ~ Age + Weight, data = bloodpressure2)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -55.80  -8.79  -0.82   7.47 103.32 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 92.72164    0.58075   159.7   &lt;2e-16 ***
## Age          0.40463    0.00812    49.8   &lt;2e-16 ***
## Weight       0.11364    0.00700    16.2   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.5 on 8484 degrees of freedom
## Multiple R-squared:  0.286,  Adjusted R-squared:  0.286 
## F-statistic: 1.7e+03 on 2 and 8484 DF,  p-value: &lt;2e-16</code></pre>
<p>The significance of Age and Body Weight is very high, but the general correlation is very weak ( R^2 = 0.286). This can also be seen in the following plots.</p>
<div class="figure"><span id="fig:unnamed-chunk-10"></span>
<img src="/post/2018-02-08-blood-pressure_files/figure-html/unnamed-chunk-10-1.png" alt="Predicted vs Actual Blood Pressure." width="864" />
<p class="caption">
Figure 4: Predicted vs Actual Blood Pressure.
</p>
</div>
<p>Light blue line is the 1:1 line. No systematic under- or overestimation here.</p>
<p>Predicted values of the full model fall short of capturing the variability in the data. Maybe other factors have to taken into into account (but not in this blogpost).</p>
<div class="figure"><span id="fig:agepl"></span>
<img src="/post/2018-02-08-blood-pressure_files/figure-html/agepl-1.png" alt="Blood Pressure as a function of Age and Weight.  Predicted values are shown in red, observed values in black. Blue line is BP predicted a function of Age alone." width="864" />
<p class="caption">
Figure 5: Blood Pressure as a function of Age and Weight. Predicted values are shown in red, observed values in black. Blue line is BP predicted a function of Age alone.
</p>
</div>
<p>Maybe we need to split by Age-Class again?</p>
</div>
<div id="boxplots-of-blood-pressures-of-10-year-age-groups" class="section level4">
<h4>Boxplots of Blood Pressures of 10-year age groups</h4>
<div class="figure"><span id="fig:Boxplots"></span>
<img src="/post/2018-02-08-blood-pressure_files/figure-html/Boxplots-1.png" alt="Blood Pressure by Age group. Orange Symbols are sample mean and lower and upper Gaussian confidence limits based on the t-distribution." width="864" />
<p class="caption">
Figure 6: Blood Pressure by Age group. Orange Symbols are sample mean and lower and upper Gaussian confidence limits based on the t-distribution.
</p>
</div>
<p>Note that this plot is essentially the same as Figure 3, only the density plots are rotated 90 degrees.</p>
<p>Comparing this with Figure 1, the toy dataset, I think the violin plot above shows that it is the Blood Pressures from the <em>female subgroup</em> that increase linearly by age. Blood Pressures of men have already increased earlier, in their twenties. Men generally have unhealthier values also for body weight, at earlier ages.</p>
</div>
<div id="comparing-myself-with-men-of-my-similar-weight-and-bmi" class="section level4">
<h4>Comparing myself with men of my similar weight and BMI</h4>
<p>In the last years my weight was between 70 and 80 Kilos, and I was always slightly to moderately overweight, so let’s say my <a href="https://en.wikipedia.org/wiki/File:BMI_chart.svg">Body Mass Index</a> varied between 25-30.</p>
<p>Let’s build a new dataset <code>bloodpressure3</code> similar to the toy dataset from Figure 1. We’ll use our subset <code>bloodpressure2</code> from the NHANES data, by filtering with these citeria:</p>
<pre class="r"><code>bloodpressure3 &lt;- bloodpressure2 %&gt;% 
        filter(BMI &gt;= 25 , BMI &lt;=30,
               Weight &gt;=70, Weight &lt;= 80, 
               Gender == &quot;male&quot;, 
               Age &gt;= 45 ) %&gt;% 
        select(-Gender)

summary(bloodpressure3)        </code></pre>
<pre><code>##     BPSysAve        Age           Weight          BMI         prediction 
##  Min.   : 93   Min.   :45.0   Min.   :70.0   Min.   :25.1   Min.   :119  
##  1st Qu.:115   1st Qu.:50.0   1st Qu.:73.8   1st Qu.:25.7   1st Qu.:122  
##  Median :126   Median :58.0   Median :76.5   Median :26.5   Median :124  
##  Mean   :126   Mean   :59.6   Mean   :76.1   Mean   :26.8   Mean   :126  
##  3rd Qu.:134   3rd Qu.:67.0   3rd Qu.:78.3   3rd Qu.:27.9   3rd Qu.:128  
##  Max.   :179   Max.   :80.0   Max.   :80.0   Max.   :29.8   Max.   :134</code></pre>
<div class="figure"><span id="fig:bpplot"></span>
<img src="/post/2018-02-08-blood-pressure_files/figure-html/bpplot-1.png" alt="Blood pressure as a function of age and body weight. NHANES data filtered to match my own age- BMI- and weight-range. Red dots are predicted values." width="864" />
<p class="caption">
Figure 7: Blood pressure as a function of age and body weight. NHANES data filtered to match my own age- BMI- and weight-range. Red dots are predicted values.
</p>
</div>
<p>The solid blue line shows the predictions by age alone. The slope is 0.585 mmHg/yr, much lower than the slope in Figure 1 which was 0.861. The equivalent regression line from Figure 1 is shown as a dashed blue line.</p>
<p>The green dot shows my personal Age/BP data at the time of writing .</p>
<pre><code>## 
## Call:
## lm(formula = BPSysAve ~ Age + Weight, data = bloodpressure3)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -44.76  -9.51   0.61   7.25  42.40 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   66.029     33.752    1.96    0.052 .  
## Age            0.585      0.111    5.27  3.8e-07 ***
## Weight         0.337      0.439    0.77    0.444    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 16.2 on 181 degrees of freedom
## Multiple R-squared:  0.137,  Adjusted R-squared:  0.128 
## F-statistic: 14.4 on 2 and 181 DF,  p-value: 1.55e-06</code></pre>
<div class="alert alert-info"><b>What I learned from doing this:</b>
<ul>
<li> Gaining insights by switching from a tiny to a bigger dataset.
<li> New tricks with ggplot2
<li> Splitting continuous data into categories / age groups was really helpful here
<li> Compared my own health status relative to others
<li> Studied Health status of the US society as a whole.
    </ul>
I did not write everything down, though.
</div>
</div>
